#!/bin/bash
for fonts in $(ls /usr/share/figlet)
do
	echo $fonts
	figlet -f $fonts The quick brown fox jumps over the lazy dog. \n 1234567890
done
toilet -f future --gay "A E S T H E T I C                 as                       fuck"
